inherit_from: https://raw.githubusercontent.com/laurentzziu/utils/master/gems/.rubocop.yml
require:
  - rubocop-performance
  - rubocop-rspec
RSpec/InstanceVariable:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
